# Generated by Django 3.0.6 on 2020-05-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duedate',
            field=models.DateField(null=True, verbose_name='due date'),
        ),
    ]
