# Generated by Django 3.0.6 on 2020-05-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_duedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='duedate',
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='due date'),
        ),
    ]
